package com.iss_mr.optaisp;


// ############################################################################
// Hard constraints
// ############################################################################

rule "Hard last entry age"
    when
        $policy : Policy($lastEntryAge:lastEntryAge )
        Preference ($requiredAge:requiredAge)
        exists Preference(policy == $policy)
    then
        scoreHolder.addHardConstraintMatch(kcontext, $lastEntryAge - $requiredAge);
end


// ############################################################################
// Soft constraints
// ############################################################################



rule "Pre-Hospitalisation covered days"
    when
        $policy : Policy($postHospitalisationCoveredDays : postHospitalisationCoveredDays)
        Preference ($requiredPostHospitalisationCoveredDays:requiredPostHospitalisationCoveredDays)
        exists Preference(policy == $policy)
    then
        scoreHolder.addSoftConstraintMatch(kcontext, $postHospitalisationCoveredDays - $requiredPostHospitalisationCoveredDays);
end
