package com.iss_mr.integrated_shield_plan_master;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private long id;

	@org.kie.api.definition.type.Label("Applicant")
	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	private com.iss_mr.integrated_shield_plan_master.Applicant applicant;

	@org.kie.api.definition.type.Label("Issuer")
	private java.lang.String issuer;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@org.kie.api.definition.type.Label("Matched Policy")
	private com.iss_mr.integrated_shield_plan_master.Policy matchedPolicy;

	@javax.persistence.ManyToOne(fetch = javax.persistence.FetchType.EAGER, cascade = {javax.persistence.CascadeType.ALL})
	@org.kie.api.definition.type.Label(value = "Preference")
	private com.iss_mr.integrated_shield_plan_master.Preference preference;

	public Application() {
	}

	public com.iss_mr.integrated_shield_plan_master.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(
			com.iss_mr.integrated_shield_plan_master.Applicant applicant) {
		this.applicant = applicant;
	}

	public java.lang.String getIssuer() {
		return this.issuer;
	}

	public void setIssuer(java.lang.String issuer) {
		this.issuer = issuer;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public com.iss_mr.integrated_shield_plan_master.Policy getMatchedPolicy() {
		return this.matchedPolicy;
	}

	public void setMatchedPolicy(
			com.iss_mr.integrated_shield_plan_master.Policy matchedPolicy) {
		this.matchedPolicy = matchedPolicy;
	}

	public com.iss_mr.integrated_shield_plan_master.Preference getPreference() {
		return this.preference;
	}

	public void setPreference(
			com.iss_mr.integrated_shield_plan_master.Preference preference) {
		this.preference = preference;
	}

	public Application(long id,
			com.iss_mr.integrated_shield_plan_master.Applicant applicant,
			java.lang.String issuer,
			com.iss_mr.integrated_shield_plan_master.Policy matchedPolicy,
			com.iss_mr.integrated_shield_plan_master.Preference preference) {
		this.id = id;
		this.applicant = applicant;
		this.issuer = issuer;
		this.matchedPolicy = matchedPolicy;
		this.preference = preference;
	}

}