package com.iss_mr.integrated_shield_plan_master;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("NRIC")
	private String id;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("Age")
	private java.lang.Integer age;

	@org.kie.api.definition.type.Label(value = "Gender")
	private java.lang.String gender;

	@org.kie.api.definition.type.Label(value = "Nationality")
	private java.lang.String nationality;

	@org.kie.api.definition.type.Label(value = "Singapore Status")
	private java.lang.String spstatus;

	public Applicant() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getGender() {
		return this.gender;
	}

	public void setGender(java.lang.String gender) {
		this.gender = gender;
	}

	public java.lang.String getNationality() {
		return this.nationality;
	}

	public void setNationality(java.lang.String nationality) {
		this.nationality = nationality;
	}

	public java.lang.String getSpstatus() {
		return this.spstatus;
	}

	public void setSpstatus(java.lang.String spstatus) {
		this.spstatus = spstatus;
	}

	public Applicant(java.lang.String id, java.lang.String name,
			java.lang.Integer age, java.lang.String gender,
			java.lang.String nationality, java.lang.String spstatus) {
		this.id = id;
		this.name = name;
		this.age = age;
		this.gender = gender;
		this.nationality = nationality;
		this.spstatus = spstatus;
	}

}