package com.iss_mr.integrated_shield_plan_master;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Policy implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "Insurer")
	private java.lang.String insurer;

	@org.kie.api.definition.type.Label(value = "Benefit")
	private java.lang.String benefit;

	public Policy() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getInsurer() {
		return this.insurer;
	}

	public void setInsurer(java.lang.String insurer) {
		this.insurer = insurer;
	}

	public java.lang.String getBenefit() {
		return this.benefit;
	}

	public void setBenefit(java.lang.String benefit) {
		this.benefit = benefit;
	}

	public Policy(java.lang.String name, java.lang.String insurer,
			java.lang.String benefit) {
		this.name = name;
		this.insurer = insurer;
		this.benefit = benefit;
	}

}