package com.iss_mr.integrated_shield_plan_master;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Preference implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Pre Hospitalisation Covered Days")
	private PreferenceMatrix preHospitalisationCoveredDays;
	@org.kie.api.definition.type.Label("Post Hospitalisation Covered Days")
	private PreferenceMatrix postHospitalisationCoveredDays;
	@org.kie.api.definition.type.Label("Policy Year Limit")
	private PreferenceMatrix policyYearLimit;
	@org.kie.api.definition.type.Label("Community Hospital")
	private PreferenceMatrix communityHospital;
	@org.kie.api.definition.type.Label("Major Organ Transplant")
	private PreferenceMatrix majorOrganTransplant;
	@org.kie.api.definition.type.Label("Critical Illnesses")
	private PreferenceMatrix criticalIllnesses;
	@org.kie.api.definition.type.Label("Prosthesis")
	private PreferenceMatrix prosthesis;
	@org.kie.api.definition.type.Label("Emergency overseas treatment")
	private PreferenceMatrix emergencyOverseasTreatment;
	@org.kie.api.definition.type.Label("Claims Processing Duration")
	private PreferenceMatrix claimsProcessingDuration;

	public Preference() {
	}

	public com.iss_mr.integrated_shield_plan_master.PreferenceMatrix getPreHospitalisationCoveredDays() {
		return this.preHospitalisationCoveredDays;
	}

	public void setPreHospitalisationCoveredDays(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix preHospitalisationCoveredDays) {
		this.preHospitalisationCoveredDays = preHospitalisationCoveredDays;
	}

	public com.iss_mr.integrated_shield_plan_master.PreferenceMatrix getPostHospitalisationCoveredDays() {
		return this.postHospitalisationCoveredDays;
	}

	public void setPostHospitalisationCoveredDays(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix postHospitalisationCoveredDays) {
		this.postHospitalisationCoveredDays = postHospitalisationCoveredDays;
	}

	public com.iss_mr.integrated_shield_plan_master.PreferenceMatrix getPolicyYearLimit() {
		return this.policyYearLimit;
	}

	public void setPolicyYearLimit(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix policyYearLimit) {
		this.policyYearLimit = policyYearLimit;
	}

	public com.iss_mr.integrated_shield_plan_master.PreferenceMatrix getCommunityHospital() {
		return this.communityHospital;
	}

	public void setCommunityHospital(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix communityHospital) {
		this.communityHospital = communityHospital;
	}

	public com.iss_mr.integrated_shield_plan_master.PreferenceMatrix getMajorOrganTransplant() {
		return this.majorOrganTransplant;
	}

	public void setMajorOrganTransplant(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix majorOrganTransplant) {
		this.majorOrganTransplant = majorOrganTransplant;
	}

	public com.iss_mr.integrated_shield_plan_master.PreferenceMatrix getCriticalIllnesses() {
		return this.criticalIllnesses;
	}

	public void setCriticalIllnesses(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix criticalIllnesses) {
		this.criticalIllnesses = criticalIllnesses;
	}

	public com.iss_mr.integrated_shield_plan_master.PreferenceMatrix getProsthesis() {
		return this.prosthesis;
	}

	public void setProsthesis(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix prosthesis) {
		this.prosthesis = prosthesis;
	}

	public com.iss_mr.integrated_shield_plan_master.PreferenceMatrix getEmergencyOverseasTreatment() {
		return this.emergencyOverseasTreatment;
	}

	public void setEmergencyOverseasTreatment(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix emergencyOverseasTreatment) {
		this.emergencyOverseasTreatment = emergencyOverseasTreatment;
	}

	public com.iss_mr.integrated_shield_plan_master.PreferenceMatrix getClaimsProcessingDuration() {
		return this.claimsProcessingDuration;
	}

	public void setClaimsProcessingDuration(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix claimsProcessingDuration) {
		this.claimsProcessingDuration = claimsProcessingDuration;
	}

	public Preference(
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix preHospitalisationCoveredDays,
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix postHospitalisationCoveredDays,
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix policyYearLimit,
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix communityHospital,
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix majorOrganTransplant,
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix criticalIllnesses,
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix prosthesis,
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix emergencyOverseasTreatment,
			com.iss_mr.integrated_shield_plan_master.PreferenceMatrix claimsProcessingDuration) {
		this.preHospitalisationCoveredDays = preHospitalisationCoveredDays;
		this.postHospitalisationCoveredDays = postHospitalisationCoveredDays;
		this.policyYearLimit = policyYearLimit;
		this.communityHospital = communityHospital;
		this.majorOrganTransplant = majorOrganTransplant;
		this.criticalIllnesses = criticalIllnesses;
		this.prosthesis = prosthesis;
		this.emergencyOverseasTreatment = emergencyOverseasTreatment;
		this.claimsProcessingDuration = claimsProcessingDuration;
	}

}