package com.iss_mr.integrated_shield_plan_master;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Validation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String result;

	public Validation() {
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public Validation(java.lang.String result) {
		this.result = result;
	}

}