package com.iss_mr.optaisp;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Policy implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID")
	private java.lang.Integer id;
	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("Daily Ward")
	private java.lang.Integer dailyWard;
	@org.kie.api.definition.type.Label("Major Organ Transplant")
	private java.lang.Integer majorOrganTransplant;
	@org.kie.api.definition.type.Label("Post-Hospitalisation Covered Days")
	private java.lang.Integer postHospitalisationCoveredDays;
	@org.kie.api.definition.type.Label("Pre-Hospitalisation Covered Days")
	private java.lang.Integer preHospitalisationCoveredDays;
	@org.kie.api.definition.type.Label("Surgery")
	private java.lang.Integer surgery;
	@org.kie.api.definition.type.Label("Last Entry Age")
	private java.lang.Integer lastEntryAge;

	@org.kie.api.definition.type.Label(value = "Premium")
	private java.util.List<com.iss_mr.optaisp.Premium> premium;

	public Policy() {
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getDailyWard() {
		return this.dailyWard;
	}

	public void setDailyWard(java.lang.Integer dailyWard) {
		this.dailyWard = dailyWard;
	}

	public java.lang.Integer getMajorOrganTransplant() {
		return this.majorOrganTransplant;
	}

	public void setMajorOrganTransplant(java.lang.Integer majorOrganTransplant) {
		this.majorOrganTransplant = majorOrganTransplant;
	}

	public java.lang.Integer getPostHospitalisationCoveredDays() {
		return this.postHospitalisationCoveredDays;
	}

	public void setPostHospitalisationCoveredDays(
			java.lang.Integer postHospitalisationCoveredDays) {
		this.postHospitalisationCoveredDays = postHospitalisationCoveredDays;
	}

	public java.lang.Integer getPreHospitalisationCoveredDays() {
		return this.preHospitalisationCoveredDays;
	}

	public void setPreHospitalisationCoveredDays(
			java.lang.Integer preHospitalisationCoveredDays) {
		this.preHospitalisationCoveredDays = preHospitalisationCoveredDays;
	}

	public java.lang.Integer getSurgery() {
		return this.surgery;
	}

	public void setSurgery(java.lang.Integer surgery) {
		this.surgery = surgery;
	}

	public java.lang.Integer getLastEntryAge() {
		return this.lastEntryAge;
	}

	public void setLastEntryAge(java.lang.Integer lastEntryAge) {
		this.lastEntryAge = lastEntryAge;
	}

	public java.util.List<com.iss_mr.optaisp.Premium> getPremium() {
		return this.premium;
	}

	public void setPremium(java.util.List<com.iss_mr.optaisp.Premium> premium) {
		this.premium = premium;
	}

	public Policy(java.lang.Integer id, java.lang.String name,
			java.lang.Integer dailyWard,
			java.lang.Integer majorOrganTransplant,
			java.lang.Integer postHospitalisationCoveredDays,
			java.lang.Integer preHospitalisationCoveredDays,
			java.lang.Integer surgery, java.lang.Integer lastEntryAge,
			java.util.List<com.iss_mr.optaisp.Premium> premium) {
		this.id = id;
		this.name = name;
		this.dailyWard = dailyWard;
		this.majorOrganTransplant = majorOrganTransplant;
		this.postHospitalisationCoveredDays = postHospitalisationCoveredDays;
		this.preHospitalisationCoveredDays = preHospitalisationCoveredDays;
		this.surgery = surgery;
		this.lastEntryAge = lastEntryAge;
		this.premium = premium;
	}

}