package com.iss_mr.optaisp;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.entity.PlanningEntity
public class Preference implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Required Daily Ward")
	private java.lang.Integer requiredDailyWard;
	@org.kie.api.definition.type.Label("Required Surgery")
	private java.lang.Integer requiredSurgery;
	@org.kie.api.definition.type.Label("Required Pre-Hospitalisation Covered Days")
	private java.lang.Integer requiredPreHospitalisationCoveredDays;
	@org.kie.api.definition.type.Label("Required Post-Hospitalisation Covered Days")
	private java.lang.Integer requiredPostHospitalisationCoveredDays;

	@org.kie.api.definition.type.Label("Required Major Organ Transplant")
	private java.lang.Integer requiredMajorOrganTransplant;

	@org.kie.api.definition.type.Label("Required Age")
	private java.lang.Integer requiredAge;

	@org.kie.api.definition.type.Label("Policy")
	@org.optaplanner.core.api.domain.variable.PlanningVariable(valueRangeProviderRefs = {"policyRange"})
	private com.iss_mr.optaisp.Policy policy;

	public Preference() {
	}

	public java.lang.Integer getRequiredDailyWard() {
		return this.requiredDailyWard;
	}

	public void setRequiredDailyWard(java.lang.Integer requiredDailyWard) {
		this.requiredDailyWard = requiredDailyWard;
	}

	public java.lang.Integer getRequiredSurgery() {
		return this.requiredSurgery;
	}

	public void setRequiredSurgery(java.lang.Integer requiredSurgery) {
		this.requiredSurgery = requiredSurgery;
	}

	public java.lang.Integer getRequiredPreHospitalisationCoveredDays() {
		return this.requiredPreHospitalisationCoveredDays;
	}

	public void setRequiredPreHospitalisationCoveredDays(
			java.lang.Integer requiredPreHospitalisationCoveredDays) {
		this.requiredPreHospitalisationCoveredDays = requiredPreHospitalisationCoveredDays;
	}

	public java.lang.Integer getRequiredPostHospitalisationCoveredDays() {
		return this.requiredPostHospitalisationCoveredDays;
	}

	public void setRequiredPostHospitalisationCoveredDays(
			java.lang.Integer requiredPostHospitalisationCoveredDays) {
		this.requiredPostHospitalisationCoveredDays = requiredPostHospitalisationCoveredDays;
	}

	public java.lang.Integer getRequiredMajorOrganTransplant() {
		return this.requiredMajorOrganTransplant;
	}

	public void setRequiredMajorOrganTransplant(
			java.lang.Integer requiredMajorOrganTransplant) {
		this.requiredMajorOrganTransplant = requiredMajorOrganTransplant;
	}

	public java.lang.Integer getRequiredAge() {
		return this.requiredAge;
	}

	public void setRequiredAge(java.lang.Integer requiredAge) {
		this.requiredAge = requiredAge;
	}

	public com.iss_mr.optaisp.Policy getPolicy() {
		return this.policy;
	}

	public void setPolicy(com.iss_mr.optaisp.Policy policy) {
		this.policy = policy;
	}

	public Preference(java.lang.Integer requiredDailyWard,
			java.lang.Integer requiredSurgery,
			java.lang.Integer requiredPreHospitalisationCoveredDays,
			java.lang.Integer requiredPostHospitalisationCoveredDays,
			java.lang.Integer requiredMajorOrganTransplant,
			java.lang.Integer requiredAge, com.iss_mr.optaisp.Policy policy) {
		this.requiredDailyWard = requiredDailyWard;
		this.requiredSurgery = requiredSurgery;
		this.requiredPreHospitalisationCoveredDays = requiredPreHospitalisationCoveredDays;
		this.requiredPostHospitalisationCoveredDays = requiredPostHospitalisationCoveredDays;
		this.requiredMajorOrganTransplant = requiredMajorOrganTransplant;
		this.requiredAge = requiredAge;
		this.policy = policy;
	}

}