package com.iss_mr.optaisp;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Premium implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Age Group")
	private java.lang.Integer ageGroup;
	@org.kie.api.definition.type.Label(value = "premium")
	private java.lang.Integer premiumByAge;

	public Premium() {
	}

	public java.lang.Integer getAgeGroup() {
		return this.ageGroup;
	}

	public void setAgeGroup(java.lang.Integer ageGroup) {
		this.ageGroup = ageGroup;
	}

	public java.lang.Integer getPremiumByAge() {
		return this.premiumByAge;
	}

	public void setPremiumByAge(java.lang.Integer premiumByAge) {
		this.premiumByAge = premiumByAge;
	}

	public Premium(java.lang.Integer ageGroup, java.lang.Integer premiumByAge) {
		this.ageGroup = ageGroup;
		this.premiumByAge = premiumByAge;
	}

}