package com.iss_mr.optaisp;
import java.util.List;
import java.util.ArrayList;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class SolverTest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SolverTest() {
        
    //@Test
    public void solve() {

        KieContainer kieContainer = KieServices.Factory.get().getKieClasspathContainer(SolverTest.class.getClassLoader());
        SolverFactory<CloudSolution> solverFactory =
                SolverFactory.createFromKieContainerXmlResource(kieContainer,
                                                                "com/iss_mr/optaisp/ispSolverConfig.xml");
        Solver<CloudSolution> solver = solverFactory.buildSolver();

        solver.solve(getSolution());
    }

    private ISPSolution getSolution() {
        Policy policy = new Policy();
        policy.setId(1);
        policy.setName("AIA HealthShield Gold Max A");
        policy.setDailyWard(100);
        policy.setMajorOrganTransplant(100);
        policy.setPostHospitalisationCoveredDays(50);
        policy.setPreHospitalisationCoveredDays(50);
        policy.setSurgery(100);
        policy.setLastEntryAge(100);
        List<Premium> premiumList =new ArrayLIst();
        Premium premium30=new Premium();
        premium30.setAgeGroup(30);
        premium30.setPremiumByAge(442);
        premiumList.add(premium30);
        
        Premium premium40=new Premium();
        premium40.setAgeGroup(40);
        premium40.setPremiumByAge(644);
        premiumList.add(premium40);
        
        Policy policy2 = new Policy();
        policy2.setId(2);
        policy2.setName("Prudential PruShield Premier");
        policy2.setDailyWard(100);
        policy2.setMajorOrganTransplant(100);
        policy2.setPostHospitalisationCoveredDays(100);
        policy2.setPreHospitalisationCoveredDays(100);
        policy2.setSurgery(100);
        policy2.setLastEntryAge(100);
        List<Premium> premiumList2 =new ArrayLIst();
        Premium premium30_2=new Premium();
        premium30_2.setAgeGroup(30);
        premium30_2.setPremiumByAge(442);
        premiumList2.add(premium30_2);
        
        Premium premium40_2=new Premium();
        premium40_2.setAgeGroup(40);
        premium40_2.setPremiumByAge(644);
        premiumList2.add(premium40_2);
        
        List<Policy> policyList=new ArrayList();
        policyList.add(policy);
        policyList.add(policy2);
        
        Preference preference = new Preference();
        preference.setRequiredDailyWard(100);
        preference.setRequiredSurgery(100);
        preference.setRequiredPreHospitalisationCoveredDays(75);
        preference.setRequiredPostHospitalisationCoveredDays(75);
        preference.setRequiredMajorOrganTransplant(100);
        preference.setRequiredAge(30);
        
        

        return new ISPSolution(policyList,
                                 Arrays.asList(preference),
                                 null);
    }
    }




}